<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Huishoudplanner.Domain\Huishoudplanner.Domain.csproj" />
  </ItemGroup>

</Project>
