<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Huishoudplanner.Domain\Huishoudplanner.Domain.csproj" />
    <ProjectReference Include="..\..\src\Huishoudplanner.Application\Huishoudplanner.Application.csproj" />
    <ProjectReference Include="..\..\src\Huishoudplanner.Adapters.Mongo\Huishoudplanner.Adapters.Mongo.csproj" />
    <ProjectReference Include="..\..\src\Huishoudplanner.Adapters.Http\Huishoudplanner.Adapters.Http.csproj" />
    <ProjectReference Include="..\..\src\Huishoudplanner.Host\Huishoudplanner.Host.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="Testcontainers.MongoDb" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

</Project>
